2016-04-08 14:10:36,983 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:11:50,733 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:12:40,313 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:14:33,776 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:17:28,658 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:21:54,298 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:36:02,868 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:36:03,753 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:38:51,900 INFO: microblog startup [in D:/python/my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:38:53,506 INFO: microblog startup [in D:/python/my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:39:48,608 INFO: microblog startup [in D:/python/my-microblog\app\__init__.py:(lineno)d]
2016-04-08 14:39:50,128 INFO: microblog startup [in D:/python/my-microblog\app\__init__.py:(lineno)d]
2016-04-08 15:08:42,836 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:(lineno)d]
2016-04-08 15:08:57,924 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 69, in login
    
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:09:18,520 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:(lineno)d]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 69, in login
    
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:11:35,272 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:11:37,234 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 68, in login
    providers=app.config['OPENID_PROVIDERS'])
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:17:04,980 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 68, in login
    providers=app.config['OPENID_PROVIDERS'])
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:17:07,351 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 68, in login
    providers=app.config['OPENID_PROVIDERS'])
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:17:09,032 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 68, in login
    providers=app.config['OPENID_PROVIDERS'])
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:17:09,776 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 68, in login
    providers=app.config['OPENID_PROVIDERS'])
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:17:10,621 ERROR: Exception on /login [GET] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 68, in login
    providers=app.config['OPENID_PROVIDERS'])
KeyError: 'OPENID_PROVIDERS'
2016-04-08 15:19:19,740 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:20:00,413 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:20:35,019 ERROR: Exception on /login [POST] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 42, in login
    if user.nickname is not nickname:
AttributeError: 'NoneType' object has no attribute 'nickname'
2016-04-08 15:22:48,526 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:22:58,496 ERROR: Exception on /login [POST] [in D:\python\my-microblog\flask\lib\site-packages\flask\app.py:1423]
Traceback (most recent call last):
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\my-microblog\flask\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\my-microblog\app\views.py", line 48, in login
    if user.nickname is not nickname:
AttributeError: 'NoneType' object has no attribute 'nickname'
2016-04-08 15:24:01,644 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:24:54,509 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:24:55,677 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:26:45,742 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:26:46,559 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 15:39:39,510 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:09:55,141 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:47:45,612 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:47:46,388 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:50:25,187 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:50:26,078 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:52:22,190 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:52:53,196 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:53:15,724 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:54:26,441 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:54:41,783 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:55:28,579 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:56:22,612 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 16:56:23,407 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:00:55,529 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:00:56,375 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:21:45,555 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:21:59,078 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:21:59,907 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:36:33,701 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:36:34,490 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:38:29,092 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:38:29,946 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:39:44,736 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:39:45,525 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:41:14,210 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:41:15,056 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:42:40,470 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:42:41,305 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:44:22,790 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:44:23,605 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:46:24,677 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:46:25,506 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:48:19,714 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:48:20,555 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:49:14,573 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:49:17,645 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:49:18,467 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:51:06,375 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:51:07,249 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:54:59,187 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
2016-04-08 17:55:00,055 INFO: microblog startup [in D:\python\my-microblog\app\__init__.py:28]
